version: "3"

includes:
  os: ./task/Taskfile_{{OS}}.yml

tasks:
  default:
    cmds:
      - task: kitty
      - task: nvim
      - task: tmux
      - task: yabai
      - task: zsh
  btop:
    cmds:
      - mkdir -p ~/.config/btop
      - stow -v -t ~/.config/btop btop
  kitty:
    cmds:
      - mkdir -p ~/.config/kitty
      - stow -v -t ~/.config/kitty kitty
  nvim:
    cmds:
      - mkdir -p ~/.config/nvim
      - stow -v -t ~/.config/nvim nvim
  openrgb:
    cmds:
      - mkdir -p ~/.config/OpenRGB
      - stow -v -t ~/.config/OpenRGB openrgb
  scripts:
    cmds:
      - stow -v -t ~ scripts
  starship:
    cmds:
      - stow -v -t ~/.config starship
  waybar:
    cmds:
      - mkdir -p ~/.config/waybar
      - stow -v -t ~/.config/waybar waybar
  wezterm:
    cmds:
      - mkdir -p ~/.config/wezterm
      - stow -v -t ~/.config/wezterm wezterm
      - touch ~/.config/wezterm/theme.bin
      - echo "dark" > ~/.config/wezterm/theme.bin
  tmux:
    cmds:
      - mkdir -p ~/.config/tmux
      - stow -v -t ~/.config/tmux tmux
