version: "3"

tasks:
  default:
    cmds:
      - task: kitty
      - task: nvim
      - task: tmux
      - task: yabai
      - task: zsh
  linux:
    cmds:
      - task: kitty
      - task: nvim
      - task: tmux
      - task: zsh
  macos:
    cmds:
      - task: kitty
      - task: nvim
      - task: tmux
      - task: yabai
      - task: zsh
  kitty:
    cmds:
      - mkdir -p ~/.config/kitty
      - stow -v -t ~/.config/kitty kitty
  nvim:
    cmds:
      - mkdir -p ~/.config/nvim
      - stow -v -t ~/.config/nvim nvim
  tmux:
    cmds:
      - mkdir -p ~/.config/tmux
      - stow -v -t ~/.config/tmux tmux
  yabai:
    cmds:
      - mkdir -p ~/.config/yabai
      - stow -v -t ~/.config/yabai yabai
  zsh:
    cmds:
      - stow -v zsh
